SESSIONS_API_URL = "https://api.openf1.org/v1/sessions"
SESSION_RESULTS_API_URL = "https://api.openf1.org/v1/session_result"
DRIVERS_API_URL = "https://api.openf1.org/v1/drivers"
LAPS_API_URL = "https://api.openf1.org/v1/laps"
STINTS_API_URL = "https://api.openf1.org/v1/stints"
RACE_CONTROL_API_URL = "https://api.openf1.org/v1/race_control"
